// DC_AutopilotProtocol.h was generated by ProtoGen version 2.2.d

#ifndef _DC_AUTOPILOTPROTOCOL_H
#define _DC_AUTOPILOTPROTOCOL_H

// C++ compilers: don't mangle us
#ifdef __cplusplus
extern "C" {
#endif

/*!
 * \file
 * \mainpage DC_Autopilot protocol stack
 *

 *
 * The protocol API enumeration is incremented anytime the protocol is changed
 * in a way that affects compatibility with earlier versions of the protocol.
 * The protocol enumeration for this version is: 1
 *
 * The protocol version is 1.0
 */

#include <stdint.h>
#include "drone_can_packet.h"	// DroneCAN packet definition

//! \return the protocol API enumeration
#define getDC_AutopilotApi() 1

//! \return the protocol version string
#define getDC_AutopilotVersion() "1.0"


// The prototypes below provide an interface to the packets.
// They are not auto-generated functions, but must be hand-written

//! \return the packet data pointer from the packet
uint8_t* getDC_AutopilotPacketData(DC_Packet_t* pkt);

//! \return the packet data pointer from the packet, const
const uint8_t* getDC_AutopilotPacketDataConst(const DC_Packet_t* pkt);

//! Complete a packet after the data have been encoded
void finishDC_AutopilotPacket(DC_Packet_t* pkt, int size, uint32_t packetID);

//! \return the size of a packet from the packet header
int getDC_AutopilotPacketSize(const DC_Packet_t* pkt);

//! \return the ID of a packet from the packet header
uint32_t getDC_AutopilotPacketID(const DC_Packet_t* pkt);

#ifdef __cplusplus
}
#endif
#endif
