// DC_BlockProtocol.c was generated by ProtoGen version 2.2.d

#include "DC_BlockProtocol.h"

/*!
 * \brief Lookup label for 'DroneCAN_BlockDataEndpoints' enum entry
 * 
 * \param value is the integer value of the enum entry
 * \return string label of the given entry (emptry string if not found)
 */
const char* DroneCAN_BlockDataEndpoints_EnumLabel(int value)
{
    switch (value)
    {
    default:
        return "";
    case DC_BLOCK_ENDPOINT_MULTI_FRAME:
        return "DC_BLOCK_ENDPOINT_MULTI_FRAME";
    case DC_BLOCK_ENDPOINT_BOOTLOADER:
        return "DC_BLOCK_ENDPOINT_BOOTLOADER";
    case DC_BLOCK_ENDPOINT_INVALID:
        return "DC_BLOCK_ENDPOINT_INVALID";
    }
}

// end of DC_BlockProtocol.c
