// DC_CommandProtocol.c was generated by ProtoGen version 2.3.b

/*
 * This program source code file is part of DroneCAN protocol specification
 *
 * Website: www.dronecan.org
 * GitHub: www.github.com/dronecan
 *
 * Copyright (C) 2017 Currawong Engineering Pty Ltd, see AUTHORS.txt for contributors.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, you may find one here:
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 * or you may search the http://www.gnu.org website for the version 2 license,
 * or you may write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
 */

#include "DC_CommandProtocol.h"

/*!
 * \brief Lookup label for 'DroneCAN_CommandMessages' enum entry
 * 
 * \param value is the integer value of the enum entry
 * \return string label of the given entry (emptry string if not found)
 */
const char* DroneCAN_CommandMessages_EnumLabel(int value)
{
    switch (value)
    {
    default:
        return "";
    case DC_PKT_CMD_DISARM:
        return "DC_PKT_CMD_DISARM";
    case DC_PKT_CMD_ARM:
        return "DC_PKT_CMD_ARM";
    case DC_PKT_CMD_BRAKE:
        return "DC_PKT_CMD_BRAKE";
    case DC_PKT_CMD_RAW_VALUE:
        return "DC_PKT_CMD_RAW_VALUE";
    case DC_PKT_CMD_TARGET_PWM:
        return "DC_PKT_CMD_TARGET_PWM";
    case DC_PKT_CMD_TARGET_RPM:
        return "DC_PKT_CMD_TARGET_RPM";
    case DC_PKT_CMD_TARGET_ANGLE:
        return "DC_PKT_CMD_TARGET_ANGLE";
    case DC_PKT_CMD_ENGINE_START:
        return "DC_PKT_CMD_ENGINE_START";
    case DC_PKT_CMD_CANCEL_START:
        return "DC_PKT_CMD_CANCEL_START";
    case DC_PKT_CMD_ENGINE_KILL:
        return "DC_PKT_CMD_ENGINE_KILL";
    case DC_PKT_CMD_THROTTLE:
        return "DC_PKT_CMD_THROTTLE";
    case DC_PKT_CMD_INDICATOR:
        return "DC_PKT_CMD_INDICATOR";
    }
}

// end of DC_CommandProtocol.c
