// DC_CommandProtocol.c was generated by ProtoGen version 2.2.d

#include "DC_CommandProtocol.h"

/*!
 * \brief Lookup label for 'DroneCAN_CommandMessages' enum entry
 * 
 * \param value is the integer value of the enum entry
 * \return string label of the given entry (emptry string if not found)
 */
const char* DroneCAN_CommandMessages_EnumLabel(int value)
{
    switch (value)
    {
    default:
        return "";
    case DC_PKT_CMD_DISARM:
        return "DC_PKT_CMD_DISARM";
    case DC_PKT_CMD_ARM:
        return "DC_PKT_CMD_ARM";
    case DC_PKT_CMD_BRAKE:
        return "DC_PKT_CMD_BRAKE";
    case DC_PKT_CMD_RAW_VALUE:
        return "DC_PKT_CMD_RAW_VALUE";
    case DC_PKT_CMD_TARGET_PWM:
        return "DC_PKT_CMD_TARGET_PWM";
    case DC_PKT_CMD_TARGET_RPM:
        return "DC_PKT_CMD_TARGET_RPM";
    case DC_PKT_CMD_TARGET_ANGLE:
        return "DC_PKT_CMD_TARGET_ANGLE";
    case DC_PKT_CMD_ENGINE_START:
        return "DC_PKT_CMD_ENGINE_START";
    case DC_PKT_CMD_CANCEL_START:
        return "DC_PKT_CMD_CANCEL_START";
    case DC_PKT_CMD_ENGINE_KILL:
        return "DC_PKT_CMD_ENGINE_KILL";
    case DC_PKT_CMD_THROTTLE:
        return "DC_PKT_CMD_THROTTLE";
    case DC_PKT_CMD_INDICATOR:
        return "DC_PKT_CMD_INDICATOR";
    }
}

// end of DC_CommandProtocol.c
