// dc_pkt_cmd.c was generated by ProtoGen version 2.3.b

/*
 * This program source code file is part of DroneCAN protocol specification
 *
 * Website: www.dronecan.org
 * GitHub: www.github.com/dronecan
 *
 * Copyright (C) 2017 Currawong Engineering Pty Ltd, see AUTHORS.txt for contributors.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, you may find one here:
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 * or you may search the http://www.gnu.org website for the version 2 license,
 * or you may write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
 */

#include "dc_pkt_cmd.h"
#include "fielddecode.h"
#include "fieldencode.h"
#include "scaleddecode.h"
#include "scaledencode.h"

/*!
 * \brief Create the DC_Cmd_RawCommand packet
 *
 * Raw actuator command
 * \param pkt points to the packet which will be created by this function
 * \param value is 
 */
void encodeDC_Cmd_RawCommandPacket(DC_Packet_t* pkt, int16_t value)
{
    uint8_t* data = getDC_CommandPacketData(pkt);
    int byteindex = 0;

    int16ToBeBytes((int16_t)value, data, &byteindex);

    // complete the process of creating the packet
    finishDC_CommandPacket(pkt, byteindex, getDC_Cmd_RawCommandPacketID());
}

/*!
 * \brief Decode the DC_Cmd_RawCommand packet
 *
 * Raw actuator command
 * \param pkt points to the packet being decoded by this function
 * \param value receives 
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */
int decodeDC_Cmd_RawCommandPacket(const DC_Packet_t* pkt, int16_t* value)
{
    int byteindex = 0;
    const uint8_t* data = getDC_CommandPacketDataConst(pkt);
    int numBytes = getDC_CommandPacketSize(pkt);

    // Verify the packet identifier
    if(getDC_CommandPacketID(pkt) != getDC_Cmd_RawCommandPacketID())
        return 0;

    if(numBytes < getDC_Cmd_RawCommandMinDataLength())
        return 0;

    *value = (int16_t)int16FromBeBytes(data, &byteindex);

    return 1;
}

/*!
 * \brief Create the DC_Cmd_PWMCommand packet
 *
 * PWM command
 * \param pkt points to the packet which will be created by this function
 * \param pwm is PWM command (us)
 */
void encodeDC_Cmd_PWMCommandPacket(DC_Packet_t* pkt, uint16_t pwm)
{
    uint8_t* data = getDC_CommandPacketData(pkt);
    int byteindex = 0;

    // PWM command (us)
    uint16ToBeBytes((uint16_t)pwm, data, &byteindex);

    // complete the process of creating the packet
    finishDC_CommandPacket(pkt, byteindex, getDC_Cmd_PWMCommandPacketID());
}

/*!
 * \brief Decode the DC_Cmd_PWMCommand packet
 *
 * PWM command
 * \param pkt points to the packet being decoded by this function
 * \param pwm receives PWM command (us)
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */
int decodeDC_Cmd_PWMCommandPacket(const DC_Packet_t* pkt, uint16_t* pwm)
{
    int byteindex = 0;
    const uint8_t* data = getDC_CommandPacketDataConst(pkt);
    int numBytes = getDC_CommandPacketSize(pkt);

    // Verify the packet identifier
    if(getDC_CommandPacketID(pkt) != getDC_Cmd_PWMCommandPacketID())
        return 0;

    if(numBytes < getDC_Cmd_PWMCommandMinDataLength())
        return 0;

    // PWM command (us)
    *pwm = (uint16_t)uint16FromBeBytes(data, &byteindex);

    return 1;
}

/*!
 * \brief Create the DC_Cmd_ThrottleCommand packet
 *
 * Throttle position command
 * \param pkt points to the packet which will be created by this function
 * \param throttle is Throttle command, 0.1% per bit
 */
void encodeDC_Cmd_ThrottleCommandPacket(DC_Packet_t* pkt, uint16_t throttle)
{
    uint8_t* data = getDC_CommandPacketData(pkt);
    int byteindex = 0;
    unsigned int tempbitfield = 0;

    // Reserved for future use
    data[byteindex] = 0;

    // Throttle command, 0.1% per bit
    tempbitfield = throttle;
    if(tempbitfield > 4095)
        tempbitfield = 4095;

    data[byteindex + 1] = (uint8_t)tempbitfield;

    tempbitfield >>= 8;
    data[byteindex] |= (uint8_t)tempbitfield;
    byteindex += 2; // close bit field

    // complete the process of creating the packet
    finishDC_CommandPacket(pkt, byteindex, getDC_Cmd_ThrottleCommandPacketID());
}

/*!
 * \brief Decode the DC_Cmd_ThrottleCommand packet
 *
 * Throttle position command
 * \param pkt points to the packet being decoded by this function
 * \param throttle receives Throttle command, 0.1% per bit
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */
int decodeDC_Cmd_ThrottleCommandPacket(const DC_Packet_t* pkt, uint16_t* throttle)
{
    unsigned int tempbitfield = 0;
    int byteindex = 0;
    const uint8_t* data = getDC_CommandPacketDataConst(pkt);
    int numBytes = getDC_CommandPacketSize(pkt);

    // Verify the packet identifier
    if(getDC_CommandPacketID(pkt) != getDC_Cmd_ThrottleCommandPacketID())
        return 0;

    if(numBytes < getDC_Cmd_ThrottleCommandMinDataLength())
        return 0;

    // Reserved for future use

    // Throttle command, 0.1% per bit
    tempbitfield = (data[byteindex] & 0xF);

    tempbitfield <<= 8;
    tempbitfield |= data[byteindex + 1];

    (*throttle) = tempbitfield;
    byteindex += 2; // close bit field

    return 1;
}
// end of dc_pkt_cmd.c
