// dc_pkt_block.c was generated by ProtoGen version 2.2.d

#include "dc_pkt_block.h"
#include "fielddecode.h"
#include "fieldencode.h"
#include "scaleddecode.h"
#include "scaledencode.h"

/*!
 * \brief Create the DC_Block_StartBlockTransfer packet
 *

 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */
void encodeDC_Block_StartBlockTransferPacketStructure(DC_Packet_t* pkt, const DC_Block_StartBlockTransfer_t* user)
{
    uint8_t* data = getDC_BlockPacketData(pkt);
    int byteindex = 0;

    // Transfer ID
    uint8ToBytes((uint8_t)user->id, data, &byteindex);

    // Transfer endpoint
    uint8ToBytes((uint8_t)user->endpoint, data, &byteindex);

    // Transfer address
    uint32ToBeBytes((uint32_t)user->address, data, &byteindex);

    // Transfer size (bytes)
    uint16ToBeBytes((uint16_t)user->size, data, &byteindex);

    // complete the process of creating the packet
    finishDC_BlockPacket(pkt, byteindex, getDC_Block_StartBlockTransferPacketID());
}

/*!
 * \brief Decode the DC_Block_StartBlockTransfer packet
 *

 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */
int decodeDC_Block_StartBlockTransferPacketStructure(const DC_Packet_t* pkt, DC_Block_StartBlockTransfer_t* user)
{
    int numBytes;
    int byteindex = 0;
    const uint8_t* data;

    // Verify the packet identifier
    if(getDC_BlockPacketID(pkt) != getDC_Block_StartBlockTransferPacketID())
        return 0;

    // Verify the packet size
    numBytes = getDC_BlockPacketSize(pkt);
    if(numBytes < getDC_Block_StartBlockTransferMinDataLength())
        return 0;

    // The raw data from the packet
    data = getDC_BlockPacketDataConst(pkt);

    // Transfer ID
    user->id = (uint8_t)uint8FromBytes(data, &byteindex);

    // Transfer endpoint
    user->endpoint = (uint8_t)uint8FromBytes(data, &byteindex);

    // Transfer address
    user->address = (uint32_t)uint32FromBeBytes(data, &byteindex);

    // Transfer size (bytes)
    user->size = (uint16_t)uint16FromBeBytes(data, &byteindex);

    return 1;
}
// end of dc_pkt_block.c
