// DC_SystemProtocol.c was generated by ProtoGen version 2.3.b

/*
 * This program source code file is part of DroneCAN protocol specification
 *
 * Website: www.dronecan.org
 * GitHub: www.github.com/dronecan
 *
 * Copyright (C) 2017 Currawong Engineering Pty Ltd, see AUTHORS.txt for contributors.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, you may find one here:
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 * or you may search the http://www.gnu.org website for the version 2 license,
 * or you may write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
 */

#include "DC_SystemProtocol.h"

/*!
 * \brief Lookup label for 'DroneCAN_SystemMessages' enum entry
 * 
 * \param value is the integer value of the enum entry
 * \return string label of the given entry (emptry string if not found)
 */
const char* DroneCAN_SystemMessages_EnumLabel(int value)
{
    switch (value)
    {
    default:
        return "";
    case DC_PKT_SYS_INFO:
        return "DC_PKT_SYS_INFO";
    case DC_PKT_SYS_ID:
        return "DC_PKT_SYS_ID";
    case DC_PKT_SYS_FW_VERSION:
        return "DC_PKT_SYS_FW_VERSION";
    case DC_PKT_SYS_FW_DATE:
        return "DC_PKT_SYS_FW_DATE";
    case DC_PKT_SYS_FW_DESC:
        return "DC_PKT_SYS_FW_DESC";
    case DC_PKT_SYS_SETTINGS_CHK:
        return "DC_PKT_SYS_SETTINGS_CHK";
    case DC_PKT_SYS_CPU_INFO:
        return "DC_PKT_SYS_CPU_INFO";
    case DC_PKT_SYS_CMD:
        return "DC_PKT_SYS_CMD";
    case DC_PKT_SYS_RESET:
        return "DC_PKT_SYS_RESET";
    case DC_PKT_SYS_ASSIGN_NODE_ID:
        return "DC_PKT_SYS_ASSIGN_NODE_ID";
    case DC_PKT_SYS_ENTER_BOOTLOADER:
        return "DC_PKT_SYS_ENTER_BOOTLOADER";
    }
}

// end of DC_SystemProtocol.c
