// DC_Sys_UID.c was generated by ProtoGen version 2.2.d

#include "DC_Sys_UID.h"
#include "fielddecode.h"
#include "fieldencode.h"
#include "scaleddecode.h"
#include "scaledencode.h"

/*!
 * \brief Encode a DC_Sys_UID_t structure into a byte array
 *

 * \param data points to the byte array to add encoded data to
 * \param bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
 * \param user is the data to encode in the byte array
 */
void encodeDC_Sys_UID_t(uint8_t* data, int* bytecount, const DC_Sys_UID_t* user)
{
    int byteindex = *bytecount;

    // Vendor ID
    uint16ToBeBytes((uint16_t)user->VID, data, &byteindex);

    // Product ID
    uint16ToBeBytes((uint16_t)user->PID, data, &byteindex);

    // Device serial number
    uint24ToBeBytes((uint32_t)user->serial, data, &byteindex);

    *bytecount = byteindex;

}// encodeDC_Sys_UID_t

/*!
 * \brief Decode a DC_Sys_UID_t structure from a byte array
 *

 * \param data points to the byte array to decoded data from
 * \param bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
 * \param user is the data to decode from the byte array
 * \return 1 if the data are decoded, else 0. If 0 is returned bytecount will not be updated.
 */
int decodeDC_Sys_UID_t(const uint8_t* data, int* bytecount, DC_Sys_UID_t* user)
{
    int byteindex = *bytecount;

    // Vendor ID
    user->VID = (uint16_t)uint16FromBeBytes(data, &byteindex);

    // Product ID
    user->PID = (uint16_t)uint16FromBeBytes(data, &byteindex);

    // Device serial number
    user->serial = (uint32_t)uint24FromBeBytes(data, &byteindex);

    *bytecount = byteindex;

    return 1;

}// decodeDC_Sys_UID_t

// end of DC_Sys_UID.c
