// DC_SystemProtocol.c was generated by ProtoGen version 2.2.d

#include "DC_SystemProtocol.h"

/*!
 * \brief Lookup label for 'DroneCAN_SystemMessages' enum entry
 * 
 * \param value is the integer value of the enum entry
 * \return string label of the given entry (emptry string if not found)
 */
const char* DroneCAN_SystemMessages_EnumLabel(int value)
{
    switch (value)
    {
    default:
        return "";
    case DC_PKT_SYS_INFO:
        return "DC_PKT_SYS_INFO";
    case DC_PKT_SYS_ID:
        return "DC_PKT_SYS_ID";
    case DC_PKT_SYS_FW_VERSION:
        return "DC_PKT_SYS_FW_VERSION";
    case DC_PKT_SYS_FW_DATE:
        return "DC_PKT_SYS_FW_DATE";
    case DC_PKT_SYS_FW_DESC:
        return "DC_PKT_SYS_FW_DESC";
    case DC_PKT_SYS_SETTINGS_CHK:
        return "DC_PKT_SYS_SETTINGS_CHK";
    case DC_PKT_SYS_CPU_INFO:
        return "DC_PKT_SYS_CPU_INFO";
    case DC_PKT_SYS_CMD:
        return "DC_PKT_SYS_CMD";
    case DC_PKT_SYS_RESET:
        return "DC_PKT_SYS_RESET";
    case DC_PKT_SYS_ASSIGN_NODE_ID:
        return "DC_PKT_SYS_ASSIGN_NODE_ID";
    case DC_PKT_SYS_ENTER_BOOTLOADER:
        return "DC_PKT_SYS_ENTER_BOOTLOADER";
    }
}

// end of DC_SystemProtocol.c
