// DC_Sys_UID.h was generated by ProtoGen version 2.2.d

#ifndef _DC_SYS_UID_H
#define _DC_SYS_UID_H

// C++ compilers: don't mangle us
#ifdef __cplusplus
extern "C" {
#endif

/*!
 * \file
 */

#include "DC_SystemProtocol.h"

typedef struct
{
    uint16_t VID;    //!< Vendor ID
    uint16_t PID;    //!< Product ID
    uint32_t serial; //!< Device serial number
}DC_Sys_UID_t;

#define getMinLengthOfDC_Sys_UID_t() (7)

//! Encode a DC_Sys_UID_t structure into a byte array
void encodeDC_Sys_UID_t(uint8_t* data, int* bytecount, const DC_Sys_UID_t* user);

//! Decode a DC_Sys_UID_t structure from a byte array
int decodeDC_Sys_UID_t(const uint8_t* data, int* bytecount, DC_Sys_UID_t* user);

#ifdef __cplusplus
}
#endif
#endif
