// DC_TelemetryProtocol.c was generated by ProtoGen version 2.2.d

#include "DC_TelemetryProtocol.h"

/*!
 * \brief Lookup label for 'DroneCAN_TelemetryMessages' enum entry
 * 
 * \param value is the integer value of the enum entry
 * \return string label of the given entry (emptry string if not found)
 */
const char* DroneCAN_TelemetryMessages_EnumLabel(int value)
{
    switch (value)
    {
    default:
        return "";
    case DC_PKT_TELEM_STATUS:
        return "DC_PKT_TELEM_STATUS";
    case DC_PKT_TELEM_WARNING:
        return "DC_PKT_TELEM_WARNING";
    case DC_PKT_TELEM_ERRORS:
        return "DC_PKT_TELEM_ERRORS";
    }
}

// end of DC_TelemetryProtocol.c
