// dronecan_system_packets.h was generated by ProtoGen version 2.19.a

/**

Copyright (c) 2020 DroneCAN

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

**/

#ifndef _DRONECAN_SYSTEM_PACKETS_H
#define _DRONECAN_SYSTEM_PACKETS_H

// C++ compilers: don't mangle us
#ifdef __cplusplus
extern "C" {
#endif

/*!
 * \file
 */

#include "DroneCANProtocol.h"
#include "dronecan_packets.h"

//! Create the DroneCAN_DeviceStatus packet
void encodeDroneCAN_DeviceStatusPacketStructure(void* pkt);

//! Decode the DroneCAN_DeviceStatus packet
int decodeDroneCAN_DeviceStatusPacketStructure(const void* pkt);

//! Create the DroneCAN_DeviceStatus packet
void encodeDroneCAN_DeviceStatusPacket(void* pkt);

//! Decode the DroneCAN_DeviceStatus packet
int decodeDroneCAN_DeviceStatusPacket(const void* pkt);

//! return the packet ID for the DroneCAN_DeviceStatus packet
#define getDroneCAN_DeviceStatusPacketID() (PKT_DC_SYS_STATUS)

//! return the minimum encoded length for the DroneCAN_DeviceStatus packet
#define getDroneCAN_DeviceStatusMinDataLength() 0

//! return the maximum encoded length for the DroneCAN_DeviceStatus packet
#define getDroneCAN_DeviceStatusMaxDataLength() 0

/*!
 * Unique identifier for DroneCAN device
 */
typedef struct
{
    uint16_t vid;     //!< Vendor ID
    uint16_t pid;     //!< Product ID
    uint32_t serial;  //!< Device serial number
    uint8_t  address; //!< CAN node address
}DroneCAN_UniqueId_t;

//! Create the DroneCAN_UniqueId packet
void encodeDroneCAN_UniqueIdPacketStructure(void* pkt, const DroneCAN_UniqueId_t* user);

//! Decode the DroneCAN_UniqueId packet
int decodeDroneCAN_UniqueIdPacketStructure(const void* pkt, DroneCAN_UniqueId_t* user);

//! Create the DroneCAN_UniqueId packet
void encodeDroneCAN_UniqueIdPacket(void* pkt, uint16_t vid, uint16_t pid, uint32_t serial, uint8_t address);

//! Decode the DroneCAN_UniqueId packet
int decodeDroneCAN_UniqueIdPacket(const void* pkt, uint16_t* vid, uint16_t* pid, uint32_t* serial, uint8_t* address);

//! return the packet ID for the DroneCAN_UniqueId packet
#define getDroneCAN_UniqueIdPacketID() (PKT_DC_SYS_UID)

//! return the minimum encoded length for the DroneCAN_UniqueId packet
#define getDroneCAN_UniqueIdMinDataLength() (8)

//! return the maximum encoded length for the DroneCAN_UniqueId packet
#define getDroneCAN_UniqueIdMaxDataLength() (8)

//! Create the DroneCAN_ManufacturerString packet
void encodeDroneCAN_ManufacturerStringPacket(void* pkt, const char manufacturerString[64]);

//! Decode the DroneCAN_ManufacturerString packet
int decodeDroneCAN_ManufacturerStringPacket(const void* pkt, char manufacturerString[64]);

//! return the packet ID for the DroneCAN_ManufacturerString packet
#define getDroneCAN_ManufacturerStringPacketID() (PKT_DC_SYS_MANF_STRING)

//! return the minimum encoded length for the DroneCAN_ManufacturerString packet
#define getDroneCAN_ManufacturerStringMinDataLength() (1)

//! return the maximum encoded length for the DroneCAN_ManufacturerString packet
#define getDroneCAN_ManufacturerStringMaxDataLength() (64)

//! Create the DroneCAN_UserString packet
void encodeDroneCAN_UserStringPacket(void* pkt, const char userString[64]);

//! Decode the DroneCAN_UserString packet
int decodeDroneCAN_UserStringPacket(const void* pkt, char userString[64]);

//! return the packet ID for the DroneCAN_UserString packet
#define getDroneCAN_UserStringPacketID() (PKT_DC_SYS_USER_STRING)

//! return the minimum encoded length for the DroneCAN_UserString packet
#define getDroneCAN_UserStringMinDataLength() (1)

//! return the maximum encoded length for the DroneCAN_UserString packet
#define getDroneCAN_UserStringMaxDataLength() (64)

/*!
 * Firmware version information
 */
typedef struct
{
    uint8_t  versionMajor;
    uint8_t  versionMinor;
    uint8_t  versionSub;  
    uint32_t checksum;    
}DroneCAN_FirmwareVersion_t;

//! Create the DroneCAN_FirmwareVersion packet
void encodeDroneCAN_FirmwareVersionPacketStructure(void* pkt, const DroneCAN_FirmwareVersion_t* user);

//! Decode the DroneCAN_FirmwareVersion packet
int decodeDroneCAN_FirmwareVersionPacketStructure(const void* pkt, DroneCAN_FirmwareVersion_t* user);

//! Create the DroneCAN_FirmwareVersion packet
void encodeDroneCAN_FirmwareVersionPacket(void* pkt, uint8_t versionMajor, uint8_t versionMinor, uint8_t versionSub, uint32_t checksum);

//! Decode the DroneCAN_FirmwareVersion packet
int decodeDroneCAN_FirmwareVersionPacket(const void* pkt, uint8_t* versionMajor, uint8_t* versionMinor, uint8_t* versionSub, uint32_t* checksum);

//! return the packet ID for the DroneCAN_FirmwareVersion packet
#define getDroneCAN_FirmwareVersionPacketID() (PKT_DC_SYS_FW_VERSION)

//! return the minimum encoded length for the DroneCAN_FirmwareVersion packet
#define getDroneCAN_FirmwareVersionMinDataLength() (7)

//! return the maximum encoded length for the DroneCAN_FirmwareVersion packet
#define getDroneCAN_FirmwareVersionMaxDataLength() (7)

/*!
 * Firmware date information
 */
typedef struct
{
    uint16_t versionYear; 
    uint8_t  versionMonth;
    uint8_t  versionDay;  
}DroneCAN_FirmwareDate_t;

//! Create the DroneCAN_FirmwareDate packet
void encodeDroneCAN_FirmwareDatePacketStructure(void* pkt, const DroneCAN_FirmwareDate_t* user);

//! Decode the DroneCAN_FirmwareDate packet
int decodeDroneCAN_FirmwareDatePacketStructure(const void* pkt, DroneCAN_FirmwareDate_t* user);

//! Create the DroneCAN_FirmwareDate packet
void encodeDroneCAN_FirmwareDatePacket(void* pkt, uint16_t versionYear, uint8_t versionMonth, uint8_t versionDay);

//! Decode the DroneCAN_FirmwareDate packet
int decodeDroneCAN_FirmwareDatePacket(const void* pkt, uint16_t* versionYear, uint8_t* versionMonth, uint8_t* versionDay);

//! return the packet ID for the DroneCAN_FirmwareDate packet
#define getDroneCAN_FirmwareDatePacketID() (PKT_DC_SYS_FW_DATE)

//! return the minimum encoded length for the DroneCAN_FirmwareDate packet
#define getDroneCAN_FirmwareDateMinDataLength() (4)

//! return the maximum encoded length for the DroneCAN_FirmwareDate packet
#define getDroneCAN_FirmwareDateMaxDataLength() (4)

/*!
 * User-configurable settings information
 */
typedef struct
{
    uint32_t settingsChecksum; //!< Checksum of all user-configurable device settings
}DroneCAN_FirmwareSettings_t;

//! Create the DroneCAN_FirmwareSettings packet
void encodeDroneCAN_FirmwareSettingsPacketStructure(void* pkt, const DroneCAN_FirmwareSettings_t* user);

//! Decode the DroneCAN_FirmwareSettings packet
int decodeDroneCAN_FirmwareSettingsPacketStructure(const void* pkt, DroneCAN_FirmwareSettings_t* user);

//! Create the DroneCAN_FirmwareSettings packet
void encodeDroneCAN_FirmwareSettingsPacket(void* pkt, uint32_t settingsChecksum);

//! Decode the DroneCAN_FirmwareSettings packet
int decodeDroneCAN_FirmwareSettingsPacket(const void* pkt, uint32_t* settingsChecksum);

//! return the packet ID for the DroneCAN_FirmwareSettings packet
#define getDroneCAN_FirmwareSettingsPacketID() (PKT_DC_SYS_FW_SETTINGS)

//! return the minimum encoded length for the DroneCAN_FirmwareSettings packet
#define getDroneCAN_FirmwareSettingsMinDataLength() (4)

//! return the maximum encoded length for the DroneCAN_FirmwareSettings packet
#define getDroneCAN_FirmwareSettingsMaxDataLength() (4)

//! Create the DroneCAN_HardwareInfo packet
void encodeDroneCAN_HardwareInfoPacketStructure(void* pkt);

//! Decode the DroneCAN_HardwareInfo packet
int decodeDroneCAN_HardwareInfoPacketStructure(const void* pkt);

//! Create the DroneCAN_HardwareInfo packet
void encodeDroneCAN_HardwareInfoPacket(void* pkt);

//! Decode the DroneCAN_HardwareInfo packet
int decodeDroneCAN_HardwareInfoPacket(const void* pkt);

//! return the packet ID for the DroneCAN_HardwareInfo packet
#define getDroneCAN_HardwareInfoPacketID() (PKT_DC_SYS_HW_INFO)

//! return the minimum encoded length for the DroneCAN_HardwareInfo packet
#define getDroneCAN_HardwareInfoMinDataLength() 0

//! return the maximum encoded length for the DroneCAN_HardwareInfo packet
#define getDroneCAN_HardwareInfoMaxDataLength() 0

/*!
 * DroneCAN protocol information
 */
typedef struct
{
    uint16_t dcApi;        //!< Field is encoded constant.
    char     dcVersion[6]; //!< Field is encoded constant.
}DroneCAN_ProtocolInfo_t;

//! Create the DroneCAN_ProtocolInfo packet
void encodeDroneCAN_ProtocolInfoPacket(void* pkt);

//! Decode the DroneCAN_ProtocolInfo packet
int decodeDroneCAN_ProtocolInfoPacket(const void* pkt, uint16_t* dcApi, char dcVersion[6]);

//! return the packet ID for the DroneCAN_ProtocolInfo packet
#define getDroneCAN_ProtocolInfoPacketID() (PKT_DC_SYS_PROTOCOL_INFO)

//! return the minimum encoded length for the DroneCAN_ProtocolInfo packet
#define getDroneCAN_ProtocolInfoMinDataLength() (3)

//! return the maximum encoded length for the DroneCAN_ProtocolInfo packet
#define getDroneCAN_ProtocolInfoMaxDataLength() (8)

#ifdef __cplusplus
}
#endif
#endif
