// DroneCANProtocol.h was generated by ProtoGen version 2.19.a

/**

Copyright (c) 2020 DroneCAN

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

**/

#ifndef _DRONECANPROTOCOL_H
#define _DRONECANPROTOCOL_H

// C++ compilers: don't mangle us
#ifdef __cplusplus
extern "C" {
#endif

/*!
 * \file
 * \mainpage DroneCAN protocol stack
 *

 *
 * The protocol API enumeration is incremented anytime the protocol is changed
 * in a way that affects compatibility with earlier versions of the protocol.
 * The protocol enumeration for this version is: 1
 *
 * The protocol version is 1.0.0
 */

#include <stdint.h>

//! \return the protocol API enumeration
#define getDroneCANApi() 1

//! \return the protocol version string
#define getDroneCANVersion() "1.0.0"

typedef enum
{
    DRONECAN_PRIORITY_CRITICAL = 0b00,//!< Critical priority message
    DRONECAN_PRIORITY_ELEVATED = 0b01,//!< Elevated priority message
    DRONECAN_PRIORITY_NORMAL = 0b10, //!< Normal priority message
    DRONECAN_PRIORITY_LOW = 0b11     //!< Low priority message
} DroneCAN_Priority_Levels;

//! \return the label of a 'DroneCAN_Priority_Levels' enum entry, based on its value
const char* DroneCAN_Priority_Levels_EnumLabel(int value);

//! \return the title of a 'DroneCAN_Priority_Levels' enum entry, based on its value
const char* DroneCAN_Priority_Levels_EnumTitle(int value);

typedef enum
{
    DRONECAN_PARAMETER_NULL = 0x00,//!< Null (empty) parameter
    DRONECAN_PARAMETER_BYTES,    //!< Array of raw bytes (4 bytes)
    DRONECAN_PARAMETER_SINT8,    //!< Signed integer, 8-bit
    DRONECAN_PARAMETER_UINT8,    //!< Unsigned integer, 8-bit
    DRONECAN_PARAMETER_SINT16,   //!< Signed integer, 16-bit
    DRONECAN_PARAMETER_UINT16,   //!< Unsigned integer, 16-bit
    DRONECAN_PARAMETER_SINT32,   //!< Signed integer, 32-bit
    DRONECAN_PARAMETER_UINT32,   //!< Unsigned integer, 32-bit
    DRONECAN_PARAMETER_FLOAT     //!< Floating point number, 32-bit
} DroneCAN_Parameter_Types;

//! \return the label of a 'DroneCAN_Parameter_Types' enum entry, based on its value
const char* DroneCAN_Parameter_Types_EnumLabel(int value);

//! \return the title of a 'DroneCAN_Parameter_Types' enum entry, based on its value
const char* DroneCAN_Parameter_Types_EnumTitle(int value);

typedef enum
{
    DRONECAN_VENDOR_CURRAWONG = 0xCECE //!< Currawong Engineering Pty Ltd
} DroneCAN_Vendors;

//! \return the label of a 'DroneCAN_Vendors' enum entry, based on its value
const char* DroneCAN_Vendors_EnumLabel(int value);

//! \return the title of a 'DroneCAN_Vendors' enum entry, based on its value
const char* DroneCAN_Vendors_EnumTitle(int value);


// The prototypes below provide an interface to the packets.
// They are not auto-generated functions, but must be hand-written

//! \return the packet data pointer from the packet
uint8_t* getDroneCANPacketData(void* pkt);

//! \return the packet data pointer from the packet, const
const uint8_t* getDroneCANPacketDataConst(const void* pkt);

//! Complete a packet after the data have been encoded
void finishDroneCANPacket(void* pkt, int size, uint32_t packetID);

//! \return the size of a packet from the packet header
int getDroneCANPacketSize(const void* pkt);

//! \return the ID of a packet from the packet header
uint32_t getDroneCANPacketID(const void* pkt);

#ifdef __cplusplus
}
#endif
#endif
