// DroneCANProtocol.c was generated by ProtoGen version 2.19.a

/**

Copyright (c) 2020 DroneCAN

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

**/

#include "DroneCANProtocol.h"

/*!
 * \brief Lookup label for 'DroneCAN_Priority_Levels' enum entry
 * 
 * \param value is the integer value of the enum entry
 * \return string label of the given entry
 */
const char* DroneCAN_Priority_Levels_EnumLabel(int value)
{
    switch (value)
    {
    default:
        return "";
    case DRONECAN_PRIORITY_CRITICAL:
        return "DRONECAN_PRIORITY_CRITICAL";
    case DRONECAN_PRIORITY_ELEVATED:
        return "DRONECAN_PRIORITY_ELEVATED";
    case DRONECAN_PRIORITY_NORMAL:
        return "DRONECAN_PRIORITY_NORMAL";
    case DRONECAN_PRIORITY_LOW:
        return "DRONECAN_PRIORITY_LOW";
    }
}

/*!
 * \brief Lookup title for 'DroneCAN_Priority_Levels' enum entry
 * 
 * \param value is the integer value of the enum entry
 * \return string title of the given entry (label name if no title given)
 */
const char* DroneCAN_Priority_Levels_EnumTitle(int value)
{
    switch (value)
    {
    default:
        return "";
    case DRONECAN_PRIORITY_CRITICAL:
        return "Critical priority message";
    case DRONECAN_PRIORITY_ELEVATED:
        return "Elevated priority message";
    case DRONECAN_PRIORITY_NORMAL:
        return "Normal priority message";
    case DRONECAN_PRIORITY_LOW:
        return "Low priority message";
    }
}


/*!
 * \brief Lookup label for 'DroneCAN_Vendors' enum entry
 * 
 * \param value is the integer value of the enum entry
 * \return string label of the given entry
 */
const char* DroneCAN_Vendors_EnumLabel(int value)
{
    switch (value)
    {
    default:
        return "";
    case DRONECAN_VENDOR_CURRAWONG:
        return "DRONECAN_VENDOR_CURRAWONG";
    }
}

/*!
 * \brief Lookup title for 'DroneCAN_Vendors' enum entry
 * 
 * \param value is the integer value of the enum entry
 * \return string title of the given entry (label name if no title given)
 */
const char* DroneCAN_Vendors_EnumTitle(int value)
{
    switch (value)
    {
    default:
        return "";
    case DRONECAN_VENDOR_CURRAWONG:
        return "Currawong Engineering Pty Ltd";
    }
}

// end of DroneCANProtocol.c
